/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.chen.weixin.test;

public final class R {
    public static final class anim {
        public static final int slider_down_anim=0x7f040000;
        public static final int slider_left_anim=0x7f040001;
        public static final int slider_right_anim=0x7f040002;
        public static final int slider_up_anim=0x7f040003;
        public static final int translate_bottom=0x7f040004;
        public static final int translate_left=0x7f040005;
        public static final int translate_right=0x7f040006;
        public static final int translate_top=0x7f040007;
        public static final int zoom_out_enter=0x7f040008;
        public static final int zoom_out_exit=0x7f040009;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int TextColor=0x7f050000;
        public static final int bgColor=0x7f050001;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int bg=0x7f020000;
        public static final int button_bg=0x7f020001;
        public static final int dog=0x7f020002;
        public static final int down1=0x7f020003;
        public static final int down2=0x7f020004;
        public static final int down3=0x7f020005;
        public static final int down4=0x7f020006;
        public static final int down5=0x7f020007;
        public static final int down6=0x7f020008;
        public static final int down7=0x7f020009;
        public static final int firstview=0x7f02000a;
        public static final int guester=0x7f02000b;
        public static final int ic_launcher=0x7f02000c;
        public static final int left1=0x7f02000d;
        public static final int left2=0x7f02000e;
        public static final int left3=0x7f02000f;
        public static final int left4=0x7f020010;
        public static final int left5=0x7f020011;
        public static final int left6=0x7f020012;
        public static final int left7=0x7f020013;
        public static final int p1=0x7f020014;
        public static final int p2=0x7f020015;
        public static final int p3=0x7f020016;
        public static final int p4=0x7f020017;
        public static final int p5=0x7f020018;
        public static final int page_indicator_bg=0x7f020019;
        public static final int page_indicator_focused=0x7f02001a;
        public static final int page_indicator_unfocused=0x7f02001b;
        public static final int phone=0x7f02001c;
        public static final int right1=0x7f02001d;
        public static final int right2=0x7f02001e;
        public static final int right3=0x7f02001f;
        public static final int right4=0x7f020020;
        public static final int right5=0x7f020021;
        public static final int right6=0x7f020022;
        public static final int right7=0x7f020023;
        public static final int s1=0x7f020024;
        public static final int s10=0x7f020025;
        public static final int s11=0x7f020026;
        public static final int s2=0x7f020027;
        public static final int s3=0x7f020028;
        public static final int s4=0x7f020029;
        public static final int s5=0x7f02002a;
        public static final int s6=0x7f02002b;
        public static final int s7=0x7f02002c;
        public static final int s8=0x7f02002d;
        public static final int s9=0x7f02002e;
        public static final int shoudao=0x7f02002f;
        public static final int up1=0x7f020030;
        public static final int up2=0x7f020031;
        public static final int up3=0x7f020032;
        public static final int up4=0x7f020033;
        public static final int up5=0x7f020034;
        public static final int up6=0x7f020035;
        public static final int up7=0x7f020036;
        public static final int whatsnew_bg=0x7f020037;
        public static final int whatsnew_btn_nor=0x7f020038;
        public static final int whatsnew_btn_pressed=0x7f020039;
        public static final int whatsnew_left=0x7f02003a;
        public static final int whatsnew_left_m=0x7f02003b;
        public static final int whatsnew_right=0x7f02003c;
        public static final int whatsnew_right_m=0x7f02003d;
        public static final int yuying=0x7f02003e;
    }
    public static final class id {
        public static final int ScrollLayout=0x7f0a0001;
        public static final int action_settings=0x7f0a001b;
        public static final int animLayout=0x7f0a0005;
        public static final int backBtn=0x7f0a0009;
        public static final int firstview=0x7f0a0016;
        public static final int guester=0x7f0a0019;
        public static final int helpBtn=0x7f0a0002;
        public static final int helpScrollL=0x7f0a0008;
        public static final int helplayout=0x7f0a000a;
        public static final int leftLayout=0x7f0a0006;
        public static final int llayout=0x7f0a0004;
        public static final int mainRLayout=0x7f0a0000;
        public static final int mytext=0x7f0a0015;
        public static final int phone=0x7f0a0018;
        public static final int phone_edit=0x7f0a000b;
        public static final int phonezi=0x7f0a001a;
        public static final int relativelayout=0x7f0a000f;
        public static final int rightLayout=0x7f0a0007;
        public static final int secondview=0x7f0a0017;
        public static final int slider_dog=0x7f0a0014;
        public static final int slider_down=0x7f0a0013;
        public static final int slider_left=0x7f0a0012;
        public static final int slider_right=0x7f0a0011;
        public static final int slider_up=0x7f0a0010;
        public static final int startBtn=0x7f0a0003;
        public static final int textView1=0x7f0a000c;
        public static final int txt_result=0x7f0a000e;
        public static final int zi=0x7f0a000d;
    }
    public static final class layout {
        public static final int activity_first=0x7f030000;
        public static final int activity_help=0x7f030001;
        public static final int activity_main=0x7f030002;
        public static final int activity_p=0x7f030003;
        public static final int dialogview=0x7f030004;
        public static final int main=0x7f030005;
        public static final int message=0x7f030006;
        public static final int message1hand=0x7f030007;
        public static final int message1handduanxin=0x7f030008;
        public static final int message1voice=0x7f030009;
        public static final int missphone=0x7f03000a;
        public static final int other=0x7f03000b;
        public static final int phone=0x7f03000c;
        public static final int phone1hand=0x7f03000d;
        public static final int phone1voice=0x7f03000e;
    }
    public static final class menu {
        public static final int about=0x7f090000;
        public static final int first=0x7f090001;
        public static final int help=0x7f090002;
        public static final int main=0x7f090003;
    }
    public static final class string {
        public static final int action_settings=0x7f070003;
        public static final int app_name=0x7f070001;
        public static final int hello=0x7f070000;
        public static final int hello_world=0x7f070004;
        public static final int title_activity_about=0x7f070006;
        public static final int title_activity_first=0x7f070005;
        public static final int title_activity_help=0x7f070007;
        public static final int title_activity_p=0x7f070002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
    }
}
